Repository DeveloperAcademy-POSTECH/2024-NC2-A13-PhotoEditing, pull requests merged in 2024-06, with the labels that each got.

#3 ✨ PR test #2
  .DS_Store
  PhotoKitsm/PhotoKitsm.xcodeproj/project.pbxproj
  PhotoKitsm/PhotoKitsm/ContentView.swift
Labels: Feat

#9 kjhjlklkjl
  PhotoKitsm/PhotoKitsm/ContentView.swift
Labels: View

#13 add models #12
  PhotoKitsm/PhotoKitsm.xcodeproj/project.pbxproj
  PhotoKitsm/PhotoKitsm/Model/CollectionModel.swift
  PhotoKitsm/PhotoKitsm/Model/PhotoEditingModel.swift
Labels: Feat

#17 Feat 데이터 연결 및 createview 기능 구현#16
  PhotoKitsm/PhotoKitsm.xcodeproj/project.pbxproj
  PhotoKitsm/PhotoKitsm/.DS_Store
  PhotoKitsm/PhotoKitsm/Model/PhotoEditingModel.swift
  PhotoKitsm/PhotoKitsm/PhotoKitsmApp.swift
  PhotoKitsm/PhotoKitsm/Tool/PhotoPicker.swift
  PhotoKitsm/PhotoKitsm/View/CompleteView.swift
  PhotoKitsm/PhotoKitsm/View/CreateView.swift
  PhotoKitsm/PhotoKitsm/View/EditView.swift
  PhotoKitsm/PhotoKitsm/View/MainView.swift
  PhotoKitsm/PhotoKitsm/View/PhotoFrameView.swift
  PhotoKitsm/PhotoKitsm/View/PhotoView.swift
Labels: Feat, Fix, View

#18 Fix 데이터 모델 연결 방식 개선 with 아이작#16
  PhotoKitsm/PhotoKitsm/Model/CollectionModel.swift
  PhotoKitsm/PhotoKitsm/Model/PhotoEditingModel.swift
  PhotoKitsm/PhotoKitsm/PhotoKitsmApp.swift
  PhotoKitsm/PhotoKitsm/View/CompleteView.swift
  PhotoKitsm/PhotoKitsm/View/CreateView.swift
  PhotoKitsm/PhotoKitsm/View/EditView.swift
  PhotoKitsm/PhotoKitsm/View/MainView.swift
  PhotoKitsm/PhotoKitsm/View/PhotoFrameView.swift
  PhotoKitsm/PhotoKitsm/View/PhotoView.swift
Labels: Fix

#22 QR이미지 추가, PhotoView 구현, 즐겨찾기 기능 구현 #19
  PhotoKitsm/PhotoKitsm.xcodeproj/project.pbxproj
  PhotoKitsm/PhotoKitsm/Assets.xcassets/QRcode.imageset/Contents.json
  PhotoKitsm/PhotoKitsm/Assets.xcassets/QRcode.imageset/githubRepositoryQRcode.png
  PhotoKitsm/PhotoKitsm/Model/CollectionModel.swift
  PhotoKitsm/PhotoKitsm/View/CompleteView.swift
  PhotoKitsm/PhotoKitsm/View/CreateView.swift
  PhotoKitsm/PhotoKitsm/View/EditView.swift
  PhotoKitsm/PhotoKitsm/View/MainView.swift
  PhotoKitsm/PhotoKitsm/View/PhotoFrameView.swift
  PhotoKitsm/PhotoKitsm/View/PhotoView.swift
Labels: Feat

#26 앨범에 저장#23
  PhotoKitsm/PhotoKitsm.xcodeproj/project.pbxproj
  PhotoKitsm/PhotoKitsm/Model/CollectionModel.swift
  PhotoKitsm/PhotoKitsm/View/PhotoView.swift
Labels: Feat

#28 Feat 크롭뷰 구현할게요#27
  PhotoKitsm/PhotoKitsm.xcodeproj/project.pbxproj
  PhotoKitsm/PhotoKitsm/Model/CollectionModel.swift
  PhotoKitsm/PhotoKitsm/View/CropView.swift
  PhotoKitsm/PhotoKitsm/View/EditView.swift
  PhotoKitsm/PhotoKitsm/View/PhotoFrameView.swift
Labels: Feat

#31 30 feat 딜리트 만들게요#30
  PhotoKitsm/PhotoKitsm/View/MainView.swift
Labels: Feat
